id = "ghostty"
name = "Ghostty"
description = "Ghostty configuration file support"
version = "0.3.2"
schema_version = 1
authors = ["Else"]
repository = "https://github.com/Else00/ghostty-zed-extension"
languages = ["languages/ghostty"]

[grammars.ghostty]
repository = "https://github.com/bezhermoso/tree-sitter-ghostty"
rev = "c14d6cb4dd36ff9dd569978491aa52e4726cbe86"

[language_servers.ghostty-lsp]
name = "Ghostty LSP"
languages = ["Ghostty"]
