name = "Ghostty"
grammar = "ghostty"
path_suffixes = [
  "ghostty/config",
  "com.mitchellh.ghostty/config",
  "config/ghostty/config",
  ".ghostty"
]
line_comments = ["#"]
scopes = ["source.ghostty"]
